//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace BuildWolfSandboxBiz
{
	/// <summary>
	/// Base class that all Table wrapping template objects inherit from.
	/// </summary>
	[System.Serializable()]
	abstract public class Business : OrmLib.BusinessBase
	{
	
		/// <summary>
		/// The data context of the underlying data row.
		/// </summary>
		internal BuildWolfSandboxBiz.DataManager DataContext;
		
		/// <summary>
		/// All the relations in the schema.
		/// </summary>
		protected System.Data.DataRelationCollection Relations;
		
		/// <summary>
		/// The associated dataset for the underlying row.
		/// </summary>
		protected System.Data.DataSet DataSet;
		
		/// <summary>
		/// Exposes the row to all classes in the assembly
		/// </summary>
		/// <value>
		/// The underlying datarow this object wraps
		/// </value>
		internal System.Data.DataRow row
		{
			get{ return base.dataRow; }
			set{ base.dataRow = value;}
		}

		/// <summary>
		/// Constructor must have a data context.
		/// </summary>
		/// <param name="dataContext">The DataManager from which to work</param>
		protected Business(BuildWolfSandboxBiz.DataManager dataContext)
		{
			DataContext = dataContext;
			DataSet = dataContext.DataSet;
		}
	}
}
